version: "3.4"

services:
  php:
    build:
      context: .
      target: app_php
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
        STABILITY: ${STABILITY:-stable}
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - php_socket:/var/run/php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      # Run "composer require symfony/mercure-bundle" to install and configure the Mercure integration
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://caddy/.well-known/mercure}
      MERCURE_PUBLIC_URL: https://${SERVER_NAME:-localhost}/.well-known/mercure
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
#nécessaire pour se connecter à l'host notamment pour Sql Server s'il est sur hôte
    extra_hosts:
      - "host.docker.internal:host-gateway"


# Mercure is installed as a Caddy module, prevent the Flex recipe from installing another service
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

#
####< doctrine/doctrine-bundle ###
#  sqlserver-db:
#    image: mcr.microsoft.com/mssql/server:2022-latest
#    ports:
#      - "1434:1433"
#    environment:
#      SA_PASSWORD: "SQLServerPasw0rd"
#      ACCEPT_EULA: "Y"
#    volumes:
#      - ./docker/sqlserver_data:/var/lib/postgresql/data:rw
#        
  encore:
    command: [ "yarn", "dev-server", "--host=0.0.0.0" ]
    build:
      context: .
      target: encore
    volumes:
      - .:/src
volumes:
  php_socket:
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###


